 docker build -t deploy-service .
 docker run -d -p 1000:1000 --name deploy-service -v /var/run/docker.sock:/var/run/docker.sock -v /usr/bin/docker:/usr/bin/docker -e TZ="Asia/Shanghai" deploy-service
